ErpBundle\Entity\Comment:
    type: entity
    table: comment
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: false
            length: 65535
            fixed: false
        issueId:
            type: integer
            nullable: true
            unsigned: false
            column: issue_id
        projectId:
            type: integer
            nullable: true
            unsigned: false
            column: project_id
        date:
            type: datetime
            nullable: false
        user:
            type: integer
            nullable: true
            unsigned: false
    lifecycleCallbacks: {  }
