ErpBundle\Entity\Issue:
    type: entity
    table: issue
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        issueName:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: issue_name
        issueDescription:
            type: text
            nullable: true
            length: 65535
            fixed: false
            column: issue_description
        issueAutor:
            type: integer
            nullable: false
            unsigned: false
            column: issue_autor
        issueExecutor:
            type: integer
            nullable: false
            unsigned: false
            column: issue_executor
        dateCreate:
            type: datetime
            nullable: false
            column: date_create
        dateFinish:
            type: datetime
            nullable: true
            column: date_finish
        status:
            type: integer
            nullable: true
            unsigned: false
            default: '1'
        summa:
            type: integer
            nullable: true
            unsigned: false
        dateStart:
            type: datetime
            nullable: true
            column: date_start
        project:
            type: integer
            nullable: true
            unsigned: false
    lifecycleCallbacks: {  }
