ErpBundle\Entity\IssueStatus:
    type: entity
    table: issue_status
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        statusName:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: status_name
    lifecycleCallbacks: {  }
