ErpBundle\Entity\ProjectType:
    type: entity
    table: project_type
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeName:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: type_name
    lifecycleCallbacks: {  }
