ErpBundle\Entity\ProjectStatus:
    type: entity
    table: project_status
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        statusName:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: status_name
    lifecycleCallbacks: {  }
