ErpBundle\Entity\ProjectCommand:
    type: entity
    table: project_command
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        issue:
            type: integer
            nullable: false
            unsigned: false
        project:
            type: integer
            nullable: false
            unsigned: false
        issueExecutor:
            type: integer
            nullable: true
            unsigned: false
            column: issue_executor
        issueAutor:
            type: integer
            nullable: true
            unsigned: false
            column: issue_autor
    lifecycleCallbacks: {  }
