ErpBundle\Entity\Role:
    type: entity
    table: role
    id:
        id:
            type: string
            nullable: false
            length: 255
            fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        roleName:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: role_name
    lifecycleCallbacks: {  }
