issue:
    path:     /
    defaults: { _controller: "ErpBundle:Issue:index" }

issue_show:
    path:     /{id}/show
    defaults: { _controller: "ErpBundle:Issue:show" }

issue_new:
    path:     /new
    defaults: { _controller: "ErpBundle:Issue:new" }

issue_create:
    path:     /create
    defaults: { _controller: "ErpBundle:Issue:create" }
    requirements: { _method: post }

issue_edit:
    path:     /{id}/edit
    defaults: { _controller: "ErpBundle:Issue:edit" }

issue_update:
    path:     /{id}/update
    defaults: { _controller: "ErpBundle:Issue:update" }
    requirements: { _method: post|put }

issue_delete:
    path:     /{id}/delete
    defaults: { _controller: "ErpBundle:Issue:delete" }
    requirements: { _method: post|delete }
