projectcommand:
    path:     /
    defaults: { _controller: "ErpBundle:ProjectCommand:index" }

projectcommand_show:
    path:     /{id}/show
    defaults: { _controller: "ErpBundle:ProjectCommand:show" }

projectcommand_new:
    path:     /new
    defaults: { _controller: "ErpBundle:ProjectCommand:new" }

projectcommand_create:
    path:     /create
    defaults: { _controller: "ErpBundle:ProjectCommand:create" }
    requirements: { _method: post }

projectcommand_edit:
    path:     /{id}/edit
    defaults: { _controller: "ErpBundle:ProjectCommand:edit" }

projectcommand_update:
    path:     /{id}/update
    defaults: { _controller: "ErpBundle:ProjectCommand:update" }
    requirements: { _method: post|put }

projectcommand_delete:
    path:     /{id}/delete
    defaults: { _controller: "ErpBundle:ProjectCommand:delete" }
    requirements: { _method: post|delete }
