site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /site

erp:
    resource: "@ErpBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

users_new_anketa:
    path:     /newanketa
    defaults: { _controller: "ErpBundle:Users:newAnketa" }
    requirements: { _method: get }

anketa_create:
    path:     /anketac
    defaults: { _controller: "ErpBundle:Users:createAnket" }
    requirements: { _method: post }

spasibo:
    path:     /spasibo
    defaults: { _controller: "ErpBundle:Users:spasibo" }
    requirements: { _method: get }



