site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }
comandos:
    path:     /comandos
    defaults: { _controller: SiteBundle:Default:comandos }
customers:
    path:     /customers
    defaults: { _controller: SiteBundle:Default:index }
portfolio:
    path:     /portfolio
    defaults: { _controller: SiteBundle:Default:index }
partner:
    path:     /partner
    defaults: { _controller: SiteBundle:Default:index }
blog:
    path:     /blog
    defaults: { _controller: SiteBundle:Default:index }
colleague:
    path:     /colleague
    defaults: { _controller: SiteBundle:Default:index }

