site_portfolio:
    resource: "@SiteBundle/Resources/config/routing/portfolio.yml"
    prefix:   /portfolio

site_blog:
    resource: "@SiteBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }

comandos:
    path:     /comandos
    defaults: { _controller: SiteBundle:Default:comandos }
customers:
    path:     /customers
    defaults: { _controller: SiteBundle:Default:customers }

portfolios:
    path:     /portfolios
    defaults: { _controller: SiteBundle:Default:Portfolios }

partner:
    path:     /partner
    defaults: { _controller: SiteBundle:Default:partners }
blog:
    path:     /blog
    defaults: { _controller: SiteBundle:Default:index }
colleague:
    path:     /colleague
    defaults: { _controller: SiteBundle:Default:colleague }

showPortfolio:
    path:     /{id}/showPortfolio
    defaults: { _controller: SiteBundle:Default:showPortfolio }
