site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }
comandos:
    path:     /comandos
    defaults: { _controller: SiteBundle:Default:comandos }
customers:
    path:     /customers
    defaults: { _controller: SiteBundle:Default:customers }
portfolio:
    path:     /portfolio
    defaults: { _controller: SiteBundle:Default:Portfolio }
partner:
    path:     /partner
    defaults: { _controller: SiteBundle:Default:partners }
blog:
    path:     /blog
    defaults: { _controller: SiteBundle:Default:index }
colleague:
    path:     /colleague
    defaults: { _controller: SiteBundle:Default:colleague }

baltspecservis:
    path:     /baltspecservis
    defaults: { _controller: SiteBundle:Default:baltspecservis }

