SiteBundle\Entity\Blog:
    type: entity
    table: blog
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
        shorttext:
            type: text
            nullable: true
            length: 65535
            fixed: false
        longtext:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
