SiteBundle\Entity\Portfolio:
    type: entity
    table: portfolio
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        colorHeaderText:
            type: string
            nullable: true
            length: 50
            fixed: false
        smallImage:
            type: string
            nullable: false
            length: 500
            fixed: false
        headerImage:
            type: string
            nullable: true
            length: 255
            fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
    lifecycleCallbacks: {  }
