portfolio:
    path:     /
    defaults: { _controller: "SiteBundle:Portfolio:index" }

portfolio_show:
    path:     /{id}/show
    defaults: { _controller: "SiteBundle:Portfolio:show" }

portfolio_new:
    path:     /new
    defaults: { _controller: "SiteBundle:Portfolio:new" }

portfolio_create:
    path:     /create
    defaults: { _controller: "SiteBundle:Portfolio:create" }
    requirements: { _method: post }

portfolio_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteBundle:Portfolio:edit" }

portfolio_update:
    path:     /{id}/update
    defaults: { _controller: "SiteBundle:Portfolio:update" }
    requirements: { _method: post|put }

portfolio_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteBundle:Portfolio:delete" }
    requirements: { _method: post|delete }
